### ISSUE TITLE
plugin no longer seems to load

### ISSUE THREAD

**Issue by EmeraldSnorlax** [powercord-community/cutecord#28]
```
Canary 125067 (3ca3109)
Host 0.0.135 Linux 64-Bit (5.17.3-Arch1-1)
Powercord v2 (b4103b0)
```

```
VM544 index.js:72 [Powercord:Plugin] An error occurred while initializing "cutecord"! /home/snorlax/Applications/powercord/src/Powercord/plugins/cutecord/index.js:329
  messageIsValid (currentUser, msgAuthor, channel) {
                                                   ^

SyntaxError: Unexpected token '{'
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at wrapSafe (internal/modules/cjs/loader.js:974:15)
    at Module._compile (internal/modules/cjs/loader.js:1034:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.o._load (electron/js2c/renderer_init.js:33:379)
console.<computed> @ VM544 index.js:72
```
i've run git pull and it is supposedly up to date

**Comment by katlyn** [comment]
Closed with #29
